name: gauntlet
channels: [conda-forge, defaults]
dependencies:
  - python=3.11
  - pip
  - pip:
      - streamlit==1.37.1
      - crewai==0.51.1
      - beautifulsoup4==4.12.3
      - lxml==5.2.2
      - tldextract==5.1.2
      - rapidfuzz==3.9.7
      - markdownify==0.13.1
      - rich==13.7.1
      - pytest==8.3.2
      - pydantic==2.8.2
